/*
*   + abstract: Java abstract keyword is used to declare an abstract class. An abstract class can provide the implementation of the interface. It can have abstract and non-abstract methods.
    + boolean: Java boolean keyword is used to declare a variable as a boolean type. It can hold True and False values only.
    + break: Java break keyword is used to break the loop or switch statement. It breaks the current flow of the program at specified conditions.
    + byte: Java byte keyword is used to declare a variable that can hold 8-bit data values.
    + case: Java case keyword is used with the switch statements to mark blocks of text.
    + catch: Java catch keyword is used to catch the exceptions generated by try statements. It must be used after the try block only.
    + char: Java char keyword is used to declare a variable that can hold unsigned 16-bit Unicode characters
    + class: Java class keyword is used to declare a class.
    + continue: Java continue keyword is used to continue the loop. It continues the current flow of the program and skips the remaining code at the specified condition.
    + default: Java default keyword is used to specify the default block of code in a switch statement.
    + do: Java do keyword is used in the control statement to declare a loop. It can iterate a part of the program several times.
    + double: Java double keyword is used to declare a variable that can hold 64-bit floating-point number.
    + else: Java else keyword is used to indicate the alternative branches in an if statement.
    + enum: Java enum keyword is used to define a fixed set of constants. Enum constructors are always private or default.
    + extends: Java extends keyword is used to indicate that a class is derived from another class or interface.
    + final: Java final keyword is used to indicate that a variable holds a constant value. It is used with a variable. It is used to restrict the user from updating the value of the variable.
    + finally: Java finally keyword indicates a block of code in a try-catch structure. This block is always executed whether an exception is handled or not.
    + float: Java float keyword is used to declare a variable that can hold a 32-bit floating-point number.
    + for: Java for keyword is used to start a for loop. It is used to execute a set of instructions/functions repeatedly when some condition becomes true. If the number of iteration is fixed, it is recommended to use for loop.
    + if: Java if keyword tests the condition. It executes the if block if the condition is true.
    + implements: Java implements keyword is used to implement an interface.
    + import: Java import keyword makes classes and interfaces available and accessible to the current source code.
    + instanceof: Java instanceof keyword is used to Check_PhoneNumber whether the object is an instance of the specified class or implements an interface.
    + int: Java int keyword is used to declare a variable that can hold a 32-bit signed integer.
    + interface: Java interface keyword is used to declare an interface. It can have only abstract methods.
    + long: Java long keyword is used to declare a variable that can hold a 64-bit integer.
    + native: Java native keyword is used to specify that a method is implemented in native code using JNI (Java Native src.java.JavaCore.Interface).
    + new: Java new keyword is used to create new objects.
    + null: Java null keyword is used to indicate that a reference does not refer to anything. It removes the garbage value.
    + package: Java package keyword is used to declare a Java package that includes the classes.
    + private: Java private keyword is an access modifier. It is used to indicate that a method or variable may be accessed only in the class in which it is declared.
    + protected: Java protected keyword is an access modifier. It can be accessible within the package and outside the package but through inheritance only. It can't be applied with the class.
    + public: Java public keyword is an access modifier. It is used to indicate that an item is accessible anywhere. It has the widest scope among all other modifiers.
    + return: Java return keyword is used to return from a method when its execution is complete.
    + short: Java short keyword is used to declare a variable that can hold a 16-bit integer.
    + static: Java static keyword is used to indicate that a variable or method is a class method. The static keyword in Java is mainly used for memory management.
    + strictfp: Java strictfp is used to restrict the floating-point calculations to ensure portability.
    + super: Java super keyword is a reference variable that is used to refer to parent class objects. It can be used to invoke the immediate parent class method.
    + switch: The Java switch keyword contains a switch statement that executes code based on Check_PhoneNumber value. The switch statement tests the equality of a variable against multiple values.
    + synchronized: Java synchronized keyword is used to specify the critical sections or methods in multithreaded code.
    + this: Java this keyword can be used to refer the current object in a method or constructor.
    + throw: The Java throw keyword is used to explicitly throw an exception. The throw keyword is mainly used to throw custom exceptions. It is followed by an instance.
    + throws: The Java throws keyword is used to declare an exception. Checked exceptions can be propagated with throws.
    + transient: Java transient keyword is used in serialization. If you define any data member as transient, it will not be serialized.
    + try: Java try keyword is used to start a block of code that will be tested for exceptions. The try block must be followed by either catch or finally block.
    + void: Java void keyword is used to specify that a method does not have a return value.
    + volatile: Java volatile keyword is used to indicate that a variable may change asynchronously.
    + while: Java while keyword is used to start a while loop. This loop iterates a part of the program several times. If the number of iteration is not fixed, it is recommended to use the while loop.
*
* */

package src.java.JavaCore.Tutorial;

public class Java_Keyworlds {
}
