name: Prettify
on:
  push:
    paths:
      - 'src/**'
      - '**.yml'
      - '**.xml'
      - '**.Dockerfile'
  pull_request:
    paths:
      - 'src/**'
      - '**.yml'
      - '**.xml'
      - '**.Dockerfile'
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Prettify code
      uses: creyD/prettier_action@v3.3
      with:
        prettier_options: --write **/*.java
        commit_message: 'Prettify code'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
